name: Build dfu-util

on:
  push:
    branches:
      - master
      - ci*
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 1 * 0'
  workflow_dispatch:
      
jobs:
  build-dfu-util:
    name: Run cross-compiler download and verification for each architecture
    strategy:
      matrix:
        arch:
          - arm-linux-musleabihf
          - aarch64-linux-musl
          
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables based on architecture
      run: |
        echo "Setting environment variables based on architecture"
        echo "xcompile_vars=CC=${{ matrix.arch }}-gcc CXX=${{ matrix.arch }}-g++ INCLUDE=\"-I/usr/${{ matrix.arch }}/include\"" >> $GITHUB_ENV
    
    - uses: actions/checkout@v4
    - name: Download musl-cross-compiler library from release
      id: musl-cross-compiler
      uses: robinraju/release-downloader@v1.8
      with:
        repository: coolitsystemsinc/cdu-lib
        latest: true
        token: ${{ secrets.ACTIONS_AUTH }}
        fileName: "${{ matrix.arch }}-cross.tgz"
        extract: false
        out-file-path: .

    - name: Copy cross-compiler to usr folder
      run: |
        tar -xvf ${{ matrix.arch }}-cross.tgz
        sudo cp -r ./${{ matrix.arch }}-cross/* /usr/

    - name: Add pandoc
      run: |
        sudo apt-get update && sudo apt-get install pandoc

    - name: Get libusb files to include
      id: libusb
      uses: robinraju/release-downloader@v1.8
      with:
        repository: coolitsystemsinc/cdu-lib
        latest: true
        token: ${{ secrets.ACTIONS_AUTH }}
        fileName: "libusb-build-${{ matrix.arch }}.zip"
        extract: true
        out-file-path: ./libusb-build/

    - name: Install libusb as a dependancy
      run: |
          sudo rm ./libusb-build/libusb-build-${{ matrix.arch }}.zip
          sudo cp -r libusb-build/* /usr/${{ matrix.arch }}/

    - name: Compile dfu-util
      run: |
        sudo ./autogen.sh
        sudo autoreconf -if
        sudo ./configure --host=${{ matrix.arch }} --prefix=/usr/${{ matrix.arch }}/ USB_CFLAGS="-I/usr/${{ matrix.arch }}/include/libusb-1.0/" USB_LIBS="-L/usr/${{ matrix.arch }}/lib/ -lusb-1.0"
        sudo chmod 777 config.h
        sudo echo "#define HAVE_NANOSLEEP 1" >> config.h
        sudo make $xcompile_vars
    
    - name: Upload dfu-util binary
      uses: actions/upload-artifact@v4
      with:
        name: dfu-util-${{ matrix.arch }}
        path: ./src/dfu-util
        
    - name: Upload dfu-prefix binary
      uses: actions/upload-artifact@v4
      with:
        name: dfu-prefix-${{ matrix.arch }}
        path: ./src/dfu-prefix
        
    - name: Upload dfu-suffix binary
      uses: actions/upload-artifact@v4
      with:
        name: dfu-suffix-${{ matrix.arch }}
        path: ./src/dfu-suffix
